##
# ODF Chart values
##
#

## If MCG multi cloud gateways stand alone is enabled, only MCG will be
#deployed no ODF/Rook/Ceph components will be used, the default SC will be use
#for the MCG database. 
#
#You can configure the limit/requests for MCG standalone by modifiying the
#odf.noobaacore and odf.noobaadb values.

mcgstandalone:
  enabled: true
# Select the storage class that will be used for the Noobaa database.
  scname: 'thin'
# An example account will be created during deployment in the openshift-storage
# namespace when createuser is enabled, although it is recommended to use object bucket claims.
  createuser:
    enabled: true
    name: demo

odf:
# ODF Version/Channel
#  channel: 'stable-4.9'
  channel: 'stable-4.10'
# Resource limits per MCG service
  noobaacore:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 700Mi
  noobaadb:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 700Mi
  noobaaendpoint:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 700Mi
