##
# ODF Chart values
##
#

## If MCG multi cloud gateways stand alone is enabled, only MCG will be
#deployed no ODF/Rook/Ceph components will be used, the default SC will be use
#for the MCG database. 
#
#You can configure the limit/requests for MCG standalone by modifiying the
#odf.noobaacore and odf.noobaadb values.

mcgstandalone:
  enabled: true
  scname: 'gp3-csi'

odf:
# ODF Version/Channel
#  channel: 'stable-4.9'
  channel: 'stable-4.10'
# Resource limits per MCG service
  noobaacore:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi
  noobaadb:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi
